apiVersion: v1
kind: Service
metadata:
  name: catfacts
  labels:
    run: catfacts
spec:
  type: LoadBalancer
  selector:
    app: catfacts
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000